# Generated by Django 5.2 on 2025-04-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_chicks', models.PositiveIntegerField()),
                ('hatch_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20, unique=True)),
                ('breed', models.CharField(max_length=50)),
                ('date_acquired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_laid', models.DateField()),
                ('number_of_eggs', models.PositiveIntegerField(default=1)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chicken')),
            ],
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_hatch_date', models.DateField()),
                ('is_hatched', models.BooleanField(default=False)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chicken')),
            ],
        ),
        migrations.DeleteModel(
            name='core',
        ),
        migrations.AddField(
            model_name='chick',
            name='incubation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incubation'),
        ),
    ]
