# Generated by Django 5.2 on 2025-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calendar_report_settings_feeding_healthstatus_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='healthstatus',
            name='chicken',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='HealthStatus',
        ),
    ]
