# Generated by Django 5.2 on 2025-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chickenenvironment_disease_healthreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
