# Generated by Django 5.2 on 2025-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_healthstatus_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('laying', 'Kuku Kutaga'), ('brooding', 'Kuatamia'), ('hatching', 'Kutotoresha'), ('vaccination', 'Chanjo'), ('order', 'Oda ya Mteja')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
