# Generated by Django 5.2.1 on 2025-05-22 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_laid', models.DateField()),
                ('number_of_eggs', models.PositiveIntegerField(default=1)),
                ('quality', models.CharField(choices=[('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C'), ('cracked', 'Cracked'), ('dirty', 'Dirty')], default='grade_a', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Average weight per egg in grams', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_eggs', to='core.chicken')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Egg Productions',
                'ordering': ['-date_laid'],
                'unique_together': {('chicken', 'date_laid')},
            },
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_hatch_date', models.DateField()),
                ('actual_hatch_date', models.DateField(blank=True, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='In Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to='core.chicken')),
                ('eggs', models.ManyToManyField(related_name='incubations', to='production.eggproduction')),
            ],
            options={
                'verbose_name_plural': 'Incubations',
                'ordering': ['-start_date'],
            },
        ),
    ]
