# Generated by Django 5.2.1 on 2025-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('kuku', 'Kuku'), ('mayai', 'Mayai'), ('incubation', 'Incubation')], max_length=20)),
            ],
        ),
    ]
