# Generated by Django 5.2.1 on 2025-05-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatch_date', models.DateField()),
                ('number_of_chicks', models.PositiveIntegerField(default=0)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_chicks', to='core.chicken')),
                ('source_incubation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.incubation')),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.breed')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
