# Generated by Django 5.2.1 on 2025-06-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Imekamilika'),
        ),
    ]
