# Generated by Django 5.2.1 on 2025-06-17 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='checkup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
